import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Felicitaciones!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1>Felicitaciones!</h1>
  <img src="https://octodex.github.com/images/NUX_Octodex.gif" alt="Description of GIF" />
  <p>Muy bien, has cofigurado correctamente un workflow automatizado para desplegar tu app de Next.js a Github Pages! 🥳</p>

      </main>
    </>
  )
}
